# This file describes an application. You can have multiple applications
# in the same project.

# The name of this app. Must be unique within a project.
name: app

# The runtime the application uses.
type: "php:7.3"

# Additional extensions
runtime:
    extensions:
        - redis

# Configuration of the build of the application.
build:
    flavor: composer

# The relationships of the application with services or other applications.
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
relationships:
    database: "db:mysql"
    redis: "rediscache:redis"

# The size of the persistent disk of the application (in MB).
disk: 2048
dependencies:
    php:
        wp-cli/wp-cli-bundle: "*"
        psy/psysh: "^0.8.4"
    nodejs:
        grunt-cli: "*"

# The mounts that will be performed when the package is deployed.
mounts:
    "/web/wp-content/uploads": "shared:files/uploads"
    "/web/wp-content/cache": "shared:files/cache"
    '/tmp': 'shared:files/tmp'

# The configuration of app when it is exposed to the web.
web:
    locations:
        "/":
            # The public directory of the app, relative to its root.
            root: "web"
            # The front-controller script to send non-static requests to.
            passthru: "/index.php"
            # Wordpress has multiple roots (wp-admin) so the following is required
            index:
                - "index.php"
            # The number of seconds whitelisted (static) content should be cached.
            expires: 600
            scripts: true
            allow: true
            rules:
                ^/composer\.json:
                    allow: false
                ^/license\.txt$:
                    allow: false
                ^/readme\.html$:
                    allow: false
        "/wp-content/cache":
            root: "web/wp-content/cache"
            scripts: false
            allow: false
        "/wp-content/uploads":
            root: "web/wp-content/uploads"
            scripts: false
            allow: true

hooks:
    build: |
        set -e
        curl -sS https://platform.sh/cli/installer | php
        cd web/wp-content/themes/kesha && npm i && grunt

    deploy: |
        set -e
        wp cache flush

crons:
    snapshot:
        # Take a snapshot automatically every night at 3 am (UTC).
        spec: '0 3 * * *'
        cmd: |
            if [ "$PLATFORM_BRANCH" = master ]; then
                /app/.platformsh/bin/platform snapshot:create --yes --no-wait
            fi
    renewcert:
        # Force a redeploy at 9 am (UTC) on the 14th of every month.
        spec: '0 9 14 * *'
        cmd: |
            if [ "$PLATFORM_BRANCH" = master ]; then
                /app/.platformsh/bin/platform redeploy --yes --no-wait
            fi
